
services:

  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: app
    depends_on:
      - database
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  
volumes:
  pgdata: