services:

  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    depends_on:
      - database
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@database:5432/app_db
      SECRET_KEY: sua-chave-secreta-forte-aqui-e.nao.use.essa.em.prod
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  pgdata:
